on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Testing Github action'
        run: pwd
     
      - name: 'Testing Print '
        run: echo Mariam 

      - name: 'Print Content Before'
        run: ls  

      -uses: actions/checkout@v3   
      
      - name: 'Print Content After'
        run: ls
